### ISSUE TITLE
MPC is going to be deprecated in favor of MaxPC

### ISSUE THREAD

**Issue by eugeneia** [KeenS/arrows#16]
Hi @KeenS,

I want to deprecate MPC in favor of [MaxPC](https://github.com/eugeneia/maxpc) (not yet in Quicklisp). From my point of view MaxPC is a clear improvement in every aspect (ease of use, expressiveness, performance) over MPC, but you might disagree (it does not support ambiguous languages, and is not really monadic). This is just letting you know early that I no longer support MPC (it will remain in Quicklisp for as long as possible though, which might be forever since it does not rely on any implementation specific API).

Are you interested in transitioning to MaxPC? If so let me know any issues you have with it.

**Comment by KeenS** [comment]
@eugeneia Thank you for your notification. I like current monadic style but I'll use recommended library after it appears in quicklisp.

**Comment by eugeneia** [comment]
@KeenS Here is a write-up that explains why MaxPC is the way it is: http://mr.gy/blog/maxpc.html

**Comment by eugeneia** [comment]
MaxPC is now in Quicklisp: http://blog.quicklisp.org/2016/08/august-2016-quicklisp-dist-update-now.html

**Comment by KeenS** [comment]
thank you for your information

**Comment by KeenS** [comment]
Close as done. Will released in next Quicklisp update
