### ISSUE TITLE
I want to use auto-escape in variable.

### ISSUE THREAD

**Issue by cxxxr** [KeenS/arrows#17]
```
<html>
<body>
{{ var body }}
</body>
</html>
```

としてbodyにhtmlを埋め込みたいんですが
このままだとエスケープされるので
att-leafクラスを継承するatt-variableクラスでスロットauto-escapeをnilにする必要があるんですが
外部からそれをする方法が見つかりません

テンプレートファイルで`{{ var body auto-escape:nil }}`と指定出来ると良いんですが
それをするためにはlexerとparserに手を入れないと駄目ですね
parserに使われているmpcもmaxpcに書き換える必要もあるように見えるんですが
色々とコンフリクトしそうです

どうすればいいですか

**Comment by KeenS** [comment]
@cxxxr 
要望ありがとうございます。そういえばescapeしない方法を用意してませんでしたね。
ここのところzenekindarl自体メンテナンス出来ていないので一番の方法は「zenekindarlを使わない」になります…。新しい文法が増えるとしたらmaxpcを使うように書き換える時だと思いますがいつになるかは何も言えないです。

もしどうしても必要でかつforkせずに使いたいのであれば（どうせしばらくコンフリクトしないので）プルリクを頂ければ取り込みます。

**Comment by cxxxr** [comment]
やってみて出来ればプルリク送ってみます
