### ISSUE TITLE
Improper ASDF usage

### ISSUE THREAD

**Issue by fare** [KeenS/arrows#20]
1- You MUST NOT do a `clear-system` in your `perform` method in `zenekindarl-test`

2- The `:after` in said method, as well as the `in-package` and `defpackage` forms, are bad memories of ASDF 1, not needed and not recommended since ASDF 3 (2013).

3- The `funcall...` can be simply `(symbol-call :prove :run-test-system)`

4- It is better form to put `:defsystem-depends-on` before the forms that depend on it (in this case the `:component` form.

5- You can slurp the contents of a file with `uiop:read-file-string`; not that I recommend you do it. I believe it is poor form and doesn't help in this case.

**Comment by KeenS** [comment]
@fare Thank you for your reporting issue.
I fixed 1-4 in 4483dcd8e494acb55e2be6168c58f97a33631fea. Is this fix sufficient? (if so, I'll close this issue)

**Comment by fare** [comment]
LGTM
